### PR TITLE
Navigation for Mobile

### PR DESCRIPTION
**Pull request by whitneyrosenberg**
Adjusted the navigation section for mobile.

### CODE REVIEW

**Comment by whitneyrosenberg** [comment]
screen shot 2017-02-17 at 3 10 17 pm
screen shot 2017-02-17 at 3 10 29 pm
Doesn't fit well on mobile sized screen. For smaller sized screens we may need to ditch the rotation and just have it fill the screen.

**Comment by whitneyrosenberg** [comment]
screen shot 2017-02-17 at 3 09 34 pm
Fits well on ipad. Wondering if it would be possible to make the icon a toggle so tap to open then tap again go close? If so, I think we need to move the menu down so the entire icon is visible. 

If that won't work, then I would move the menu up to cover the entire icon. I found myself several times clicking on the icon to close and wondering why it wouldn't work.

**Comment by stoddard-david** [comment]
A click function would be nice for the navigation, but I don't know how to do it without JavaScript. I can move the menu up easily. I can move the navigation over for a small screen and remove the angle. 

I see there is a comment that you adjusted the navigation for mobile. I tried to see what was done, but I am not showing any difference. Are you working on that part? I don't want to make a change if you are working on that.

**Comment by stoddard-david** [comment]
It looks like I was reading backwards. I thought the newest was at top at first, but it appears the newest is on bottom on my screen.

**Pull request merged**
